name: Continuous integration

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod
          cache-dependency-path: ./go.mod

      - name: Build, lint, format, test
        uses: pre-commit-ci/lite-action@v1.0.1

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.61.0
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
